services:
  scrolls:
    image: ghcr.io/txpipe/scrolls:latest
    command: [ "daemon" ]
    environment:
      - RUST_LOG=info
    volumes:
      - ./daemon.toml:/etc/scrolls/daemon.toml
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
